import React, { useEffect, useState } from 'react'
import QuestionCard from '../question/QuestionCard'
import { pickRandomQuestions, generateDistractors } from '../../lib/hebrewHelpers'

export default function HebrewMode({ words, onResult }) {
  const [pool, setPool] = useState([])
  const [queue, setQueue] = useState([])
  const [current, setCurrent] = useState(null)
  const [playedAudio, setPlayedAudio] = useState(false)

  useEffect(() => {
    // filter only Hebrew words and shuffle
    const he = words || []
    setPool(he)
    setQueue(pickRandomQuestions(he, 50))
  }, [words])

  useEffect(() => {
    if (!current && queue.length) {
      setCurrent(queue[0])
      setQueue((q) => q.slice(1))
    }
  }, [queue, current])

  const handlePlayed = (type) => {
    // mark that audio (word or sentence) was played for this question
    setPlayedAudio(true)
  }

  const handleAnswer = (selectedIndex) => {
    const correct = selectedIndex === current.correct_option
    onResult({ correct, meta: { audio: playedAudio, category: current.category } })
    // reset audio flag for the next question
    setPlayedAudio(false)
    // TODO: achievements, audio feedback, avatar reactions
    setCurrent(null)
  }

  if (!current) return <div className="instructions">Loading next word...</div>

  // ensure distractors generated by algorithm (not random junk)
  const options = current.options && current.options.length === 4 ? current.options : generateDistractors(current, pool)

  return (
    <div className="hebrew-mode">
      <QuestionCard
        direction="rtl"
        audioSrc={current.audio_url}
        sentenceAudio={current.sentence_audio_url}
        //text={current.text}
        options={options}
        correctIndex={current.correct_option}
        onAnswer={handleAnswer}
        ttsText={current.text}
        ttsSentence={current.text}
        ttsLang={'he-IL'}
        onPlayAudio={handlePlayed}
      />
    </div>
  )
}
